### PR TITLE
DLPX-82095 Upgrade toolkits JDK to 8u345-b01

### PR DESCRIPTION
**Pull request by smeda-delphix**
### Description
upgrade host JDK versions to 8u345b01.
Made the code conditional to make it work for master branch with the same snippet.

corresponding jdk-archiver commit - https://github.com/delphix/jdk-archiver/pull/3

### Testing
ab-prepush : http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/3034/

### CODE REVIEW

**Comment by prakashsurya** [comment]
changes look reasonable to me.. I'd like to get an `ab-pre-push` of this on both `6.0/stage` and `master` to verify it works for both branches.. I'm not sure why, but it looks like the `ab-pre-push` linked off the PR is for `master`, and the one you manually kicked off and linked to is for `master` too..

I would have expected the automatic run would have been for `6.0/stage`, so I might need to dig into why it picked `master` as the branch to test.. when this PR is targeting `6.0/stage`:
```
± curl -s https://api.github.com/repos/delphix/host-jdks/pulls/19 | jq .base.ref
"6.0/stage"
```

In the mean time, can you apply this change on top of `6.0/stage` and manually kick off a run to verify it picks up the correct URLs for that branch?

**Comment by prakashsurya** [comment]
> DLPX-82095 Upgrade toolkits JDK to 8u345-b01 for 6.0.17.0

This PR title seems inconsistent with the changes.. we're updating only 6.1.0.0 in this PR, right? since we're only bumping the versions on `master`.. not on `6.0/stage` or 6.0.17.0.. should we change the title to match?

**Comment by smeda-delphix** [comment]
> changes look reasonable to me.. I'd like to get an `ab-pre-push` of this on both `6.0/stage` and `master` to verify it works for both branches.. I'm not sure why, but it looks like the `ab-pre-push` linked off the PR is for `master`, and the one you manually kicked off and linked to is for `master` too..
> 
> I would have expected the automatic run would have been for `6.0/stage`, so I might need to dig into why it picked `master` as the branch to test.. when this PR is targeting `6.0/stage`:
> 
> ```
> ± curl -s https://api.github.com/repos/delphix/host-jdks/pulls/19 | jq .base.ref
> "6.0/stage"
> ```
> 
> In the mean time, can you apply this change on top of `6.0/stage` and manually kick off a run to verify it picks up the correct URLs for that branch?

I was able to kick off a 6.0/stage build by specifying it in build parameters while kicking ab-prepush manually. Here's the new build - http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/3034/

**Review by prakashsurya — APPROVED** [review]
LGTM

**Review by ljiang-delphix — APPROVED** [review]
lgtm

**Pull request merged**
